FROM nginx:latest

# Nginx listen on this port
EXPOSE 80

# Remove the default config file that /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf

# Copy the requirements file in order to install Python dependencies
COPY app.conf /etc/nginx/conf.d